// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUhhYKMWQhGhs66YOWWtgz0-Mb2ynZfp4',
    appId: '1:1015412238693:android:884716e35ee63683a7998c',
    messagingSenderId: '1015412238693',
    projectId: 'auth-project-c55c0',
    databaseURL: 'https://auth-project-c55c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-project-c55c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtUESAgbk2X-JbgcDAiwgU6NXlmQTN0nc',
    appId: '1:1015412238693:ios:124c8a042353065da7998c',
    messagingSenderId: '1015412238693',
    projectId: 'auth-project-c55c0',
    databaseURL: 'https://auth-project-c55c0-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'auth-project-c55c0.appspot.com',
    androidClientId: '1015412238693-vadn8uv3e6vidkpi3q67hpocvn4ndlnf.apps.googleusercontent.com',
    iosClientId: '1015412238693-tmr3f9tv5grosvv9vmbu4snt8lqqi9di.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}